<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>AudioStreamOptimizer</AssemblyName>
    <RootNamespace>DelayDazzle.AudioStreamOptimizer</RootNamespace>
    <Version>1.0.0</Version>
    <Authors>DelayDazzle</Authors>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="StardewModdingAPI">
      <HintPath>libs/StardewModdingAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="StardewValley">
      <HintPath>libs/StardewValley.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="StardewValley.GameData">
      <HintPath>libs/StardewValley.GameData.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SMAPI.Toolkit.CoreInterfaces">
      <HintPath>libs/SMAPI.Toolkit.CoreInterfaces.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>libs/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
