name: Build SMAPI Mod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build Mod
      run: dotnet build --configuration Release

    - name: Upload Mod Files
      uses: actions/upload-artifact@v4
      with:
        name: AudioStreamOptimizer
        path: |
          bin/Release/net8.0/AudioStreamOptimizer.dll
          manifest.json
          i18n/
